
name: Prepare Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version Number'
        required: true
      changelog:
        description: 'Changelog'
        default: 'Your Version is unsupported and will no longer function properly in the near future, please update as soon as possible.'
        required: false
        type: string

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Configure version.json & Push Tag
      run: | 
            echo "version is ${{ github.event.inputs.version }}"
            git config user.name "GitHub Actions Bot"
            git config user.email "<>"
            sed -i "/is_master/d" fxmanifest.lua
            sed -i "/^version/c\version '${{ github.event.inputs.version }}'" fxmanifest.lua
            echo '{"version": "${{ github.event.inputs.version }}", "changelog": "${{ github.event.inputs.changelog }}", "fivem": {"version": "${{ github.event.inputs.version }}","changelog": "${{ github.event.inputs.changelog }}"},"redm": {"version": "${{ github.event.inputs.version }}","changelog": "${{ github.event.inputs.changelog }}"}}' > version.json
            git add .
            git commit -m "${{ github.event.inputs.version }}"
            git tag -a ${{ github.event.inputs.version }} -m "Version ${{ github.event.inputs.version }}"
            sed -i "/^version/ais_master 'yes'" fxmanifest.lua
            git add .
            git commit -m "Update Version"
            git push --follow-tags
